languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "MasterSkepticista"
copyright = "If you copy this, may your WiFi become unstable."

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts", "code"]
  description = "My personal blog"

[params.author]
  name = "Karan Shah"
  image = "img/profile.png"
  headline = "Sampling meaning from a non-stationary prior."
  bio = "Sampling meaning from a non-stationary prior."
  links = [
    { github = "https://github.com/MasterSkepticista" },
    { x-twitter = "https://twitter.com/elevated_quark" },
    { google-scholar = "https://scholar.google.com/citations?user=vEgcRTkAAAAJ&hl=en" },
    { stack-overflow = "https://stackoverflow.com/users/9230398/karan-shah" },
    { linkedin = "https://linkedin.com/in/karan-bhavesh-shah" },
  ]
